### PR TITLE
correctly close streams to fix tests

### PR DESCRIPTION
**Pull request by jtnord**
amends #167
@basil @jglick @fabricepipart1a

### Testing done

unignored test and validated failures occur. [check report](https://github.com/jenkinsci/workflow-cps-global-lib-http-plugin/pull/169/checks?check_run_id=16958919701)
closed the stream and the tests are fixed in CI

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by jglick — APPROVED** [review]
:face_exhaling: I spent a while searching unsuccessfully for leaks in `src/main/` but it did not occur to me to look in test code.

Anyway, good to know that opening a directory handle causes `Files.delete` to pass without actual deletion the first time, while an immediately following call to pass _with_ deletion. (Sprinkling in `Thread.sleep`s does not change behavior that I can see.) I would have expected either the initial `Files.delete` to fail with a message that there was an open file handle or similar; or for deletion to keep on not working for a random amount of time until the file handle was closed by GC. Perhaps the initial `delete` call releases the file handle without removing the directory, and this counts as success?!

**Comment by fabricepipart1a** [comment]
I do not know where comes the motivation to help me maintain this plugin but I warmly welcome it. Thanks guys
Indeed that one was hard to spot!

**Review by basil — COMMENTED** [review]
Sorry for messing this up and thanks!

**Comment by basil** [comment]
> I do not know where comes the motivation to help me maintain this plugin but I warmly welcome it.

The short answer is that when plugins of sufficient popularity get too far behind, this begins to create maintenance problems for Jenkins core and other plugins. This plugin was falling a little too far behind given how widely deployed it is. While I doubt we particularly enjoy having to do this, we do what is needed to sustain the overall health of the Jenkins plugin ecosystem. I want to also say that in general this plugin is quite successful, and the minor drawback of its build and test suite being behind (until recently) in no way detracts from its success.

**Pull request merged**
